-- Create Tables --
CREATE TYPE "Language" AS ENUM (
  'hindi',
  'english',
  'urdu',
  'tamil',
  'telugu',
  'gujrati',
  'kannada',
  'marathi',
  'malayalam',
  'bengali',
  'punjabi',
  'multi-language'
);

CREATE TYPE "Genre" AS ENUM (
  'drama',
  'comedy',
  'action',
  'thriller',
  'sci-fi',
  'animation',
  'biography',
  'classic',
  'crime',
  'family',
  'mystery',
  'period',
  'supernatural',
  'political'
);

CREATE TABLE "MovieLanguage"(
  "movie" bigint NOT NULL,
  "language" Language NOT NULL
);

CREATE TABLE "MovieGenre"(
  "movie" bigint NOT NULL,
  "genre" Genre NOT NULL
);

CREATE TABLE "Movie"(
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150) NOT NULL,
  "duration" integer
);

CREATE TABLE "Address"(
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city" varchar(150) NOT NULL,
  "state" varchar(150) NOT NULL,
  "latitude" float,
  "longitude" float
);

CREATE TABLE "Theatre"(
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "location" bigint
);

CREATE TABLE "Show"(
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie" bigint NOT NULL,
  "theatre" bigint NOT NULL,
  "date" date NOT NULL,
  "showtime" time NOT NULL,
  "available_seats" integer NOT NULL
);

COMMENT ON COLUMN "Movie"."duration" IS '(in minutes)';

ALTER TABLE "MovieLanguage" ADD FOREIGN KEY ("movie") REFERENCES "Movie"("id");

ALTER TABLE "MovieGenre" ADD FOREIGN KEY ("movie") REFERENCES "Movie"("id");

ALTER TABLE "Theater" ADD FOREIGN KEY ("location") REFERENCES "Address"("id");

ALTER TABLE "Show" ADD FOREIGN KEY ("movie") REFERENCES "Movie"("id");

ALTER TABLE "Show" ADD FOREIGN KEY ("theatre") REFERENCES "Theater"("id");


-- Data Entry --
INSERT INTO "Address"(city, state, latitude, longitude)
VALUES ('Gwalior', 'Madhya Pradesh', 	53.792039, -77.616743
);

INSERT INTO "Theater"(name, location)
VALUES ('PVR: Nexus', 1);

INSERT INTO "Movie"(title, duration)
VALUES ('Dasara', 120), ('Kisi Ka Bhai Kisi Ki Jaan', 150), ('Tu Jhoothi Main Makkaar', 130), ('Avatar: The Way of Water', 190);

INSERT INTO "MovieGenre"(movie, genre)
VALUES (1, 'action'),(2, 'comedy'),(3, 'drama'), (4, 'sci-fi');
	
INSERT INTO "MovieLanguage"(language, movie)
VALUES ('telugu', 1),('hindi', 2),('hindi', 3),('english', 4);
  
INSERT INTO "Show"(movie, theatre, date, showtime, available_seats)
VALUES (1, 1, '2024-03-26', '10:30:00', 50);
